version: '3.8'

services:
  # --- LOGGING (Elasticsearch) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.11
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2GB
    volumes:
      - ./architecture/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - cyber-lab

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.11
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - cyber-lab

  # --- IRIS ---
  db-iris:
    image: postgres:14-alpine
    container_name: db-iris
    environment:
      - POSTGRES_USER=iris
      - POSTGRES_PASSWORD=iris_pass
      - POSTGRES_DB=iris_db
    volumes:
      - ./architecture/iris/db_data:/var/lib/postgresql/data
    networks:
      - cyber-lab

  iris:
    image: donserdal/iris-web-webapp:latest
    container_name: iris
    ports:
      - "8000:8000"
    environment:
      - IRIS_DB_HOST=db-iris
      - IRIS_DB_NAME=iris_db
      - IRIS_DB_USER=iris
      - IRIS_DB_PASSWORD=iris_pass
    depends_on:
      - db-iris
    networks:
      - cyber-lab

  # --- soar ---
  n8n:
     image: n8nio/n8n:latest
     container_name: n8n
     ports:
       - "5678:5678"
     networks:
       - cyber-lab
     volumes:
       - ./architecture/n8n/data:/home/node/.n8n

  # --- attacker & victim ---
  evilginx:
    image: warhorse/evilginx2
    container_name: evilginx
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cyber-lab

  victim-machine:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: victim-machine
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:3000"
    shm_size: "1gb"
    volumes:
      - ./architecture/victim/config:/config
      - ./architecture/victim/logs:/var/log/victim_activity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - cyber-lab

  # --- log shipping ---
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.19.11
    container_name: filebeat
    user: root
    command: ["--strict.perms=false"]
    volumes:
      - ./architecture/victim/logs:/usr/share/filebeat/victim_logs:ro
      - ./architecture/victim/config/chromium-profile:/usr/share/filebeat/victim_logs/chromium:ro
      - ./architecture/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - cyber-lab

networks:
  cyber-lab:
    driver: bridge