packetbeat.interfaces.device: br-1040ff292ecb

packetbeat.interfaces.bpf_filter: "net 172.18.0.0/16"

packetbeat.protocols:
  - type: dns
    ports: [53]
    include_authorities: true
  - type: http
    ports: [80, 8080, 3000]
    include_body_for: ["text/html", "application/json", "application/x-www-form-urlencoded"]
    hide_keywords: ["image", "css", "js", "woff", "png", "svg"]
  - type: tls
    ports: [443]

setup.kibana:
  host: "localhost:5601"
setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]

compression_level: 6

logging.level: info